### ISSUE TITLE
Saving and Loading .obj of spatial mesh on runtime for Hololens spatial mapping

### ISSUE THREAD

**Issue by sprakhar12** [Unity3dAzure/StorageServicesDemo#11]
How about scanning the environment through hololens, saving it using voice or gesture commands and loading the saved .obj on runtime using voice or gesture commands for Hololens spatial mapping applications. Is it possible to use this service this way?

**Comment by deadlyfingers** [comment]
@sprakhar12 I have loaded in dynamic models using the [glTF](https://github.com/KhronosGroup/glTF) binary format. It ran as Windows Store App so it should also run ok as HoloLens UWP app. I haven't yet tried the .obj format, but providing there is a way to do this in Unity it should be another potential file format.

**Comment by sprakhar12** [comment]
Thanks for giving the gITF suggestion. Have to look into it.
Will keep posting and updating on .obj if something works

**Comment by deadlyfingers** [comment]
@sprakhar12 I created a separate Unity sample for loading glTF models using blob storage. [https://github.com/Unity3dAzure/StorageServicesGLTFDemo ](https://github.com/Unity3dAzure/StorageServicesGLTFDemo ) I included it as a separate sample for now due to the external plugin binary dependencies of the UnityGLFT project.
